controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
let mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ...ee...............
    ..22ee.eeeee........
    .5522eeeeeeee9......
    ..5522eeeeeee99.....
    ..5522eeeeeeee99....
    .5522eeeeeeeeeeee...
    ..22ee.eeeeeeeee..c.
    ...ee..eeeeeeee...c.
    .........c...c...cc.
    .......ccccccccccc..
    ....................
    `, SpriteKind.Player)
